export default {
    list: '/school/schoolList',
    importShcool: '/dataImport/school',
    importStuent: '/dataImport/student',
    addSchool: '/school/addSchool',
    updataSchool: '/school/updataSchool',
    addGrade: '/school/addGrade',
    updataGrade: '/school/updataGrade',
    listGrade: '/school/gradeList',
    addStudent: '/school/addStudent',
    updataStudent: '/school/updataStudent',
    listStudent: '/school/studentList',
    addGuard:  '/school/addCuard',
    updataGuard: '/school/updataGuard',
    listGuard: '/school/guardList',
    addClassTeacher: '/school/addClassTeacher',
    updataClassTeacher: '/school/updataClassTeacher',
    listClassTeacher: '/school/classTeacherList',
    listHeadthPaper:'/clock/selectHealthClock',
    listClock:'/clock/selectClockLogs',
    listClass: '/school/classList',
    addClass:'/school/addClass',
    updateClass: '/school/updataClass',
    getmyschool: '/school/getmyschool'
}